### PR TITLE
Ports NSV Small Arms

### PR DESCRIPTION
**Pull request by generichuman2**
## About The Pull Request
Ports the glocks, tazer, M4, Peacekeeper, and Peacemaker from NSV.

## Why It's Good For The Game
Because it would be really funny,

## Changelog
:cl:
add: Ports the guns over from NSV13.
/:cl:

### CODE REVIEW

**Comment by generichuman2** [comment]
fuck it, it will probably be fine

**Comment by generichuman2** [comment]
it wasn't fine

**Comment by lampstation** [comment]
i dont think it was fine

**Comment by generichuman2** [comment]
it was indeed, not fine

**Pull request closed without merging**
